# 数据库链接驱动
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 111111
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置mybatis的日志, 指定输出到控制台
    map-underscore-to-camel-case: true #开启mybatis的驼峰命名自动映射开关 a_column ------> aCloumn

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketname: gg-bond-1


jwt:
  key: h1h2h3
  algorithmName: HS256

server:
  port: 8080

#  开启事务日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


